name: Publish Docker image
on: [ push ]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          VERSION=`git rev-parse --short HEAD`
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          
          echo ::set-output name=version::${VERSION}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: cosmii02
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Registries
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64/v8
          push: true
          tags: |
            cosmiizerotsu/csgoarm64:${{ steps.prepare.outputs.version }}
            cosmiizerotsu/csgoarm64:latest
            ghcr.io/cosmii02/csgoarm64:${{ steps.prepare.outputs.version }}
            ghcr.io/cosmii02/csgoarm64:latest
